### ISSUE TITLE
AssertionError when running inference.py

### ISSUE THREAD

**Issue by vegeta41** [j-duan/VS-Net#1]
Evaluating performance for coronal_pd
/home/wzz/miniconda3/envs/vs-net/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/wzz/miniconda3/envs/vs-net/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
    Patient 11:      nan      nan      nan      nan
Traceback (most recent call last):
  File "inference.py", line 174, in <module>
    mat_dict={'normalization': np.asarray(normalization)})
  File "/home/wzz/project/VS-Net/common/mriutils.py", line 72, in saveAsMat
    assert img.ndim in [2, 3, 4]
AssertionError

how can i fix it？thanks！

**Comment by VincyDa** [comment]
您在VS-Net上提交的问题和我所遇见的问题一样，想问问您现在是否解决了

**Comment by VincyDa** [comment]
> 
您在VS-Net上提交的问题和我所遇见的问题一样，想问问您现在是否解决了

**Comment by chke097** [comment]
@VincyDa Hello, I was replicating this code recently, but there was a problem in downloading the dataset. I could not download it directly from the dataset link in GLOBUS. After many attempts, I was reminded that the download failed. So, have you successfully downloaded the dataset? Can you share it with me?Thank you!

**Comment by VincyDa** [comment]
好的，已经在github上分享网盘链接，有需要可以去取，但vs-net的代码似乎优点问题，inference.py出现错误，目前我没法解决，作者也并未解答，如果您那边可以解决的话希望可以交流一下
________________________________
发件人: chke097 ***@***.***>
发送时间: 2023年3月14日 16:50
收件人: j-duan/VS-Net ***@***.***>
抄送: VincyDa ***@***.***>; Mention ***@***.***>
主题: Re: [j-duan/VS-Net] AssertionError when running inference.py (#1)


@VincyDa<https://kor01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVincyDa&data=05%7C01%7C%7C323b7249be054375dd7508db24691cb7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638143806112516545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C1UHMa72i5xBoqgythbJY768q%2BwDYPWylkmHwfd0Dm0%3D&reserved=0> Hello, I was replicating this code recently, but there was a problem in downloading the dataset. I could not download it directly from the dataset link in GLOBUS. After many attempts, I was reminded that the download failed. So, have you successfully downloaded the dataset? Can you share it with me?Thank you!

―

**Comment by chke097** [comment]
您好，请问您有数据集下载的原始格式嘛？您分享的是tfrecord格式，如果可以的话，我们可以➕v联系



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月14日 16:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [j-duan/VS-Net] AssertionError when running inference.py (#1) |

好的，已经在github上分享网盘链接，有需要可以去取，但vs-net的代码似乎优点问题，inference.py出现错误，目前我没法解决，作者也并未解答，如果您那边可以解决的话希望可以交流一下
________________________________
发件人: chke097 ***@***.***>
发送时间: 2023年3月14日 16:50
收件人: j-duan/VS-Net ***@***.***>
抄送: VincyDa ***@***.***>; Mention ***@***.***>
主题: Re: [j-duan/VS-Net] AssertionError when running inference.py (#1)


@VincyDa<https://kor01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVincyDa&data=05%7C01%7C%7C323b7249be054375dd7508db24691cb7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638143806112516545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C1UHMa72i5xBoqgythbJY768q%2BwDYPWylkmHwfd0Dm0%3D&reserved=0> Hello, I was replicating this code recently, but there was a problem in downloading the dataset. I could not download it directly from the dataset link in GLOBUS. After many attempts, I was reminded that the download failed. So, have you successfully downloaded the dataset? Can you share it with me?Thank you!

―

**Comment by VincyDa** [comment]
原格式的正在上传，可以添加微信：ksh17786412206
________________________________
发件人: chke097 ***@***.***>
发送时间: 2023年3月14日 20:21
收件人: j-duan/VS-Net ***@***.***>
抄送: VincyDa ***@***.***>; Mention ***@***.***>
主题: Re: [j-duan/VS-Net] AssertionError when running inference.py (#1)


您好，请问您有数据集下载的原始格式嘛？您分享的是tfrecord格式，如果可以的话，我们可以➕v联系



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月14日 16:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [j-duan/VS-Net] AssertionError when running inference.py (#1) |

好的，已经在github上分享网盘链接，有需要可以去取，但vs-net的代码似乎优点问题，inference.py出现错误，目前我没法解决，作者也并未解答，如果您那边可以解决的话希望可以交流一下
________________________________
发件人: chke097 ***@***.***>
发送时间: 2023年3月14日 16:50
收件人: j-duan/VS-Net ***@***.***>
抄送: VincyDa ***@***.***>; Mention ***@***.***>
主题: Re: [j-duan/VS-Net] AssertionError when running inference.py (#1)


@VincyDa<https://kor01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVincyDa&data=05%7C01%7C%7C323b7249be054375dd7508db24691cb7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638143806112516545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C1UHMa72i5xBoqgythbJY768q%2BwDYPWylkmHwfd0Dm0%3D&reserved=0> Hello, I was replicating this code recently, but there was a problem in downloading the dataset. I could not download it directly from the dataset link in GLOBUS. After many attempts, I was reminded that the download failed. So, have you successfully downloaded the dataset? Can you share it with me?Thank you!

―
